bugdig/bugdig/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [

    # path('', admin.site.urls),
    path('admin/', admin.site.urls),
    path('cases/', include('cases.urls')),
    path('users/', include('users.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

bugdig/cases/urls.py
from django.urls import path

from . import views

app_name = 'cases'

urlpatterns = [
    path('list/', views.ListCases.as_view(), name='list'),
    path('create/', views.CreateCase.as_view(), name='create'),
    path('<int:pk>/read/', views.ReadCase.as_view(), name='read'),
    path('<int:pk>/update/', views.UpdateCase.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteCase.as_view(), name='delete'),
]

bugdig/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('list/', views.ListUsers.as_view(), name='list'),
    path('create/', views.CreateUser.as_view(), name='create'),
    path('<int:pk>/read/', views.ReadUser.as_view(), name='read'),
    path('<int:pk>/update/', views.UpdateUser.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteUser.as_view(), name='delete'),
]

bugdig/cases/models/case.py
from django.db import models
from django.utils.translation import ugettext as _

from users.models import Profile
from django.urls import reverse_lazy

class Case( models.Model ):
    """
    # Case

    Core Bugdig model

    A Case can be assigned to any number of Profile

    A Profile can be assigned to any number of Case
    """
    objects = models.Manager()

    title = models.CharField(
        unique = True,
        max_length = 60,
        verbose_name=_("title"),

    )
    description = models.TextField(
        blank = True,
        verbose_name=_("description")
    )

    date_created= models.DateTimeField( auto_now_add = True, editable=False )
    date_updated= models.DateTimeField( auto_now = True, editable=False )

    assignee = models.ManyToManyField( Profile,
        blank = True,
        verbose_name=_("assignee")
    )

    class Types (models.TextChoices):
        TASK = _('task')
        ISSUE = _('issue')
        BUG = _('bug')
        MAINTENANCE = _('maintenance')

    type_of= models.CharField(
        db_index = True,
        default = Types.TASK,
        choices = Types.choices,
        max_length = 12,
        verbose_name=_("type")
    )

    class States (models.TextChoices):
        NEW = _('new')
        ASSIGNED = _('assigned')
        FINISHED = _('finished')

    state = models.CharField(
        default = States.NEW,
        choices = States.choices,
        max_length = 12,
        verbose_name=_("state")
    )

    class Difficulties ( models.IntegerChoices ):
        EASIEST = 0
        EASY = 1
        MEDIUM = 2
        HARD = 3
        HARDEST = 4

    difficulty= models.SmallIntegerField(
        default = Difficulties.MEDIUM,
        choices = Difficulties.choices,
        verbose_name=_("difficulty")
    )

    class Priorities (models.IntegerChoices):
        LOWEST = 0
        LOW = 1
        MEDIUM = 2
        HIGH = 3
        HIGHEST = 4

    priority= models.SmallIntegerField(
        default = Priorities.MEDIUM,
        choices = Priorities.choices,
        verbose_name=_("priority")
    )

    def get_absolute_url(self):
        return reverse_lazy('cases:read', args=[self.id])

    def __str__( self ):

        assignees = tuple(self.assignee.all())

        return f"{self.id} - {self.type_of} - {self.title} - {str(assignees)}"

    def __repr__(self):
        assignees = tuple(self.assignee.all())

        return f"{self.id} - {self.type_of} - {self.title} - {str(assignees)}"

bugdig/cases/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.utils.translation import gettext as _

from cases.models import Case

class ListCases( ListView ):

    template_name = 'cases/list.html'
    model = Case
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'headers': dict(
                id          = _('id'),
                type_of     = _('type'),
                title       = _('title'),
                state       = _('state'),
                priority    = _('priority'),
                difficulty  = _('difficulty'),
                assignee    = _('assignee'),
                actions     = '',
                ),
            'txt': dict(
                title       = _('cases'),
                no_cases    = _('there\'s no cases available for this filter.' ),
                total       = _('total cases')
            )
        })

        return context
class ReadCase ( DetailView ):
    model = Case
    template_name = 'cases/read.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'titles': dict(
            id              = _('id'),
            title           = _('title'),
            description     = _('description'),
            date_created    = _('created on'),
            date_updated    = _('last updated'),
            type_of         = _('type'),
            state           = _('state'),
            priority        = _('priority'),
            difficulty      = _('difficulty'),
            assignee        = _('users assigned to this case'),
            ),
            'choices': dict(
                priority    = Case.Priorities.choices[self.object.priority][1],
                difficulty  = Case.Difficulties.choices[self.object.difficulty][1],
            )
        })
        return context

class CreateCase( CreateView ):
    model = Case
    template_name = 'cases/create_update.html'
    fields = [
        'title',
        'description',
        'assignee',
        'type_of',
        'state',
        'difficulty',
        'priority',
    ]

class UpdateCase( UpdateView ):
    model = Case
    template_name = 'cases/create_update.html'
    fields = [
        'title',
        'description',
        'assignee',
        'type_of',
        'state',
        'difficulty',
        'priority',
    ]

class DeleteCase( DeleteView ):
    model = Case
    template_name = 'cases/delete.html'
    success_url = reverse_lazy('cases:list')

bugdig/cases/templates/cases/create_update.html
{% extends 'base.html' %}

{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    {{ form }}
    <br>
    <button class="waves-effect btn blue-grey lighten-0" type="submit">Submit</button>
</form>
{% endblock content %}

bugdig/cases/templates/cases/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    <p>
        {% trans "You are about to delete case "%}<strong>{{object.title}}</strong>
        <br>
        {% trans "Are you sure?" %}
    </p>
    <button class="btn red darken-3" type="submit">{% trans "Yes, Delete" %}</button>
</form>
{% endblock content %}

bugdig/cases/templates/cases/list.html
{% extends 'base.html' %}

{% block navbar %}
  <li><a href="{% url 'cases:create' %}"><i class="material-icons">add</i></a></li>
  {{ block.super }}
{% endblock navbar %}

{% block content %}
<table id='cases-table' class='highlight responsive-table'>
  <thead>
    <tr class='blue-grey lighten-4'><th class="center-align" colspan="{{ headers|length }}">{{txt.title | capfirst }}</th></tr>
    <tr>
      <th>{{ headers.id }}</th>
      <th>{{ headers.type_of }}</th>
      <th>{{ headers.title }}</th>
      <th>{{ headers.state }}</th>
      <th>{{ headers.priority }}</th>
      <th>{{ headers.difficulty }}</th>
      <th>{{ headers.assignee }}</th>
      <th>{{ headers.actions }}</th>
    </tr>
  </thead>
  <tbody>
  {% for case in object_list %}
    <tr>
      <td>{{ case.id }}</td>
      <td>{{ case.type_of | capfirst }}</td>
      <td><a href="{% url 'cases:read' case.id %}">{{ case.title | capfirst }}</a></td>
      <td>{{ case.state }}</td>
      <td>{{ case.priority }}</td>
      <td>{{ case.difficulty }}</td>
      <td>
      {% for assignee in case.assignee.all %}
        <a href="{% url 'users:read' assignee.user.id %}">{{ assignee.user.username }}</a>
      {% endfor %}
      </td>
      <td>
        <a class="waves-effect btn blue-grey lighten-2" href="{% url 'cases:update' case.id %}"><i class="material-icons">edit</i></a>
        <a class="waves-effect btn blue-grey lighten-0" href="{% url 'cases:delete' case.id %}"><i class="material-icons">delete</i></a>
      </td>
    </tr>
  {% empty %}
    <tr>
      <td colspan="{{ headers|length }}">{{ txt.no_cases | capfirst }}</td>
    </tr>
  {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td colspan="{{ headers|length }}">{{ txt.total | capfirst }} {{ headers|length }}</td>
    </tr>
  </tfoot>
</table>
{% endblock %}

bugdig/cases/templates/cases/read.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <h5>{{ object.title }}</h5>
</div>
<div class="row">
  <span class="left">{{ titles.id | capfirst }}</span>
  <span class="right">{{ object.id }}</span>
</div>
<div class="row">
  <div>{{ titles.description | capfirst }}</div>
  <div class="card">
    <div class="card-content">{{ object.description }}</div>
  </div>
</div>
<div class="row">
  <span class="left">{{ titles.date_created | capfirst }}</span>
  <span class="right">{{ object.date_created | date:'Y-m-d' }}</span>
</div>
<div class="row">
  <span class="left">{{ titles.date_updated | capfirst }}</span>
  <span class="right">{{ object.date_updated | date:'Y-m-d'}}</span>
</div>
<div class="row">
  <span class="left">{{ titles.type_of | capfirst }}</span>
  <span class="right" class="right">{{ object.type_of | capfirst }}</span>
</div>
<div class="row">
  <span class="left">{{ titles.state | capfirst }}</span>
  <span class="right">{{ object.state | capfirst }}</span>
</div>
<div class="row">
  <span class="left">{{ titles.priority | capfirst }}</span>
  <span class="right">{{ choices.priority | capfirst }}</span>
</div>
<div class="row">
  <span class="left">{{ titles.difficulty | capfirst }}</span>
  <span class="right">{{ choices.difficulty }}</span>
</div>
<div class="row">
  <div>{{ titles.assignee | capfirst }}</div>
  <div class="divider"></div>
  <div class="collection">
    {% for assignee in object.assignee.all %}
        <a class="collection-item" href="{% url 'users:read' assignee.user.id %}">{{assignee.user.username}}</a>
    {% empty %}
        <span class="collection-item">{{txt.no_assignees}}</span>
    {% endfor %}
  </div>
</div>
{% endblock content %}