bugdig/bugdig/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [

    # path('', admin.site.urls),
    path('admin/', admin.site.urls),
    path('cases/', include('cases.urls')),
    path('users/', include('users.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

bugdig/cases/urls.py
from django.urls import path

from . import views

app_name = 'cases'

urlpatterns = [
    path('list/', views.ListCases.as_view(), name='list'),
    path('create/', views.CreateCase.as_view(), name='create'),
    path('<int:pk>/read/', views.ReadCase.as_view(), name='read'),
    path('<int:pk>/update/', views.UpdateCase.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteCase.as_view(), name='delete'),
]

bugdig/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('list/', views.ListUsers.as_view(), name='list'),
    path('create/', views.CreateUser.as_view(), name='create'),
    path('<int:pk>/read/', views.ReadUser.as_view(), name='read'),
    path('<int:pk>/update/', views.UpdateUser.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteUser.as_view(), name='delete'),
]

bugdig/users/models/profile.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.contrib.auth.models import User

class Profile ( models.Model ):
    """
    # Profile
    It's purpose is to extend the django User model.

    User model fields:
    - username
    - first_name
    - last_name
    - email
    - password
    - groups
    - user_permissions
    - is_staff
    - is_active
    - is_superuser
    - last_login
    - date_joined

    Django Users Docs:

    https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User
    """

    objects = models.Manager()

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    location = models.CharField(max_length=30, blank=True)

    date_birth = models.DateField(null=True, blank=True)

    def __str__(self ):
        return f"{self.user.username}"

    def __repr__(self ):
        return f"{self.user.username}"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

bugdig/users/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.utils.translation import gettext as _

from users.models import Profile
from django.contrib.auth.models import User

class ListUsers( ListView ):

    template_name = 'users/list.html'
    model = Profile
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'headers': dict(
                id                  = _('id'),
                username            = _('user'),
                first_name          = _('first name'),
                last_name           = _('last name'),
                email               = _('email'),
                user_permissions    = _('access level'),
                is_active           = _('enabled'),
                last_login          = _('last access'),
                actions             = '',
                ),
            'txt': dict(
                title       = _('users'),
                no_users    = _('there\'s no users available for this filter.' ),
                total       = _('Total Cases')
            )
        })

        return context
class ReadUser( DetailView ):
    model = Profile
    template_name = 'users/read.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context.update({
            'titles': dict(
                table               = _('user data'),
                id                  = _('id'),
                username            = _('user'),
                first_name          = _('first name'),
                last_name           = _('last name'),
                email               = _('email'),
                user_permissions    = _('access level'),
                is_active           = _('enabled'),
                last_login          = _('last access'),
                )
        })

        return context

class CreateUser( CreateView ):
    model = Profile
    template_name = 'users/create_update.html'
    fields = [
        'username',
        'first_name',
        'last_name',
        'email',
        'user_permissions',
        'is_active',
        'last_login',
    ]

class UpdateUser( UpdateView ):
    model = Profile
    template_name = 'users/create_update.html'
    fields = [
        'username',
        'first_name',
        'last_name',
        'email',
        'user_permissions',
        'is_active',
        'last_login',
    ]


class DeleteUser( DeleteView ):
    model = Profile
    template_name = 'users/delete.html'

    success_url = reverse_lazy('users:list')

bugdig/users/templates/users/create_update.html
{% extends 'base.html' %}

{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    {{ form }}
    <br>
    <button class="waves-effect btn blue-grey lighten-0" type="submit">Submit</button>
</form>
{% endblock content %}

bugdig/users/templates/users/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="." method="POST">
    {% csrf_token %}
    <p>
        {% trans "You are about to delete user "%}<strong>{{object.user.username}}</strong>
        <br>
        {% trans "Are you sure?" %}
    </p>
    <button class="btn red darken-3" type="submit">{% trans "Yes, Delete" %}</button>
</form>
{% endblock content %}

bugdig/users/templates/users/list.html
{% extends 'base.html' %}

{% block navbar %}
  <li><a href="{% url 'users:create' %}"><i class="material-icons">add</i></a></li>
  {{ block.super }}
{% endblock navbar %}

{% block content %}
<table id='users-table' class='highlight responsive-table'>
  <thead>
    <tr class='blue-grey lighten-4'><th class="center-align" colspan="{{ headers|length }}">{{txt.title | capfirst }}</th></tr>
    <tr>
      <th>{{ headers.id }}</th>
      <th>{{ headers.username }}</th>
      <th>{{ headers.first_name }}</th>
      <th>{{ headers.last_name }}</th>
      <th>{{ headers.email }}</th>
      <th>{{ headers.user_permissions }}</th>
      <th>{{ headers.is_active }}</th>
      <th>{{ headers.last_login }}</th>
      <th>{{ headers.actions }}</th>
    </tr>
  </thead>
  <tbody>
  {% for profile in object_list %}
    <tr>
      <td>{{ profile.id }}</td>
      <td><a href="{% url 'users:read' profile.user.id %}">{{ profile.user.username }}</a></td>
      <td>{{ profile.user.first_name | capfirst }}</td>
      <td>{{ profile.user.last_name | capfirst }}</td>
      <td>{{ profile.user.email }}</td>
      <td>{{ profile.user.user_permissions.all | unordered_list}}</td>
      <td>{{ profile.user.is_active }}</td>
      <td>{{ profile.user.last_login | date:"Y-m-d"}}</td>
      <td>
        <a class="waves-effect btn blue-grey lighten-2" href="{% url 'users:update' profile.id %}"><i class="material-icons">edit</i></a>
        <a class="waves-effect btn blue-grey lighten-0" href="{% url 'users:delete' profile.id %}"><i class="material-icons">delete</i></a>
      </td>
    </tr>
  {% empty %}
    <tr>
      <td colspan="{{ headers|length }}">{{ txt.no_users | capfirst }}</td>
    </tr>
  {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      <td>{{ txt.total }}</td>
      <td colspan="{{ headers|length|add:"-1" }}">{{ headers|length }}</td>
    </tr>
  </tfoot>
</table>
{% endblock content %}

bugdig/users/templates/users/read.html
{% extends 'base.html' %}

{% block content %}
<table class="highlight">
  <thead>
    <tr class='blue-grey lighten-4'><th colspan="2">{{titles.table | capfirst }}</th></tr>
    <tr>
      <th>{{ titles.id }}</th>
      <th>{{ object.user.id }}</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{ titles.first_name }}</td>
      <td>{{ object.user.first_name | capfirst }}</td>
    </tr>
    <tr>
      <td>{{ titles.last_name }}</td>
      <td>{{ object.user.last_name | capfirst }}</td>
    </tr>
    <tr>
      <td>{{ titles.email }}</td>
      <td>{{ object.user.email }}</td>
    </tr>
    <tr>
      <td>{{ titles.last_login }}</td>
      <td>{{ object.user.user_permissions.all | unordered_list}}</td>
    </tr>
    <tr>
      <td>{{ titles.user_permissions }}</td>
      <td>{{ object.user.is_active }}</td>
    </tr>
    <tr>
      <td>{{ titles.is_active }}</td>
      <td>{{ object.user.last_login | date:"Y-m-d"}}</td>
    </tr>
  </tbody>
</table>

{% endblock content %}